using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generator;

/// <summary>
/// Two compile-time features in one generator, so the fixture can probe both.
///
/// 1. **Source generation** — emits a `GeneratedInfo` class whose contents are
///    computed from the compilation itself, so it cannot be mistaken for
///    hand-written code.
/// 2. **Interceptors** — rewrites one specific call site to a different method,
///    which is the compile-time AOP mechanism.
///
/// Neither leaves a trace at run time beyond ordinary IL, which is exactly the
/// question the fixture is asking: does a runtime need to *support* them, or
/// does it only need to run what they produce?
/// </summary>
[Generator]
public sealed class FeatureGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // ── Source generation ───────────────────────────────────────────────
        // Count the types in the compilation so the output is demonstrably
        // derived from the source rather than a constant.
        var typeCount = context.CompilationProvider.Select((compilation, _) =>
            compilation.GlobalNamespace
                .GetNamespaceMembers()
                .SelectMany(n => n.GetTypeMembers())
                .Count(t => t.Name == "Sensor" || t.Name == "Reading"));

        context.RegisterSourceOutput(typeCount, static (production, count) =>
        {
            var source = $$"""
                // <auto-generated/> by Generator.FeatureGenerator.
                namespace AdvancedFeatures;

                internal static class GeneratedInfo
                {
                    public const int SensorCount = {{count}};
                    public static string Describe() => "from-generator";
                }
                """;
            production.AddSource("GeneratedInfo.g.cs", SourceText.From(source, Encoding.UTF8));
        });

        // ── Interceptors ────────────────────────────────────────────────────
        // Find the call to Interceptable.Which() and rewrite it.
        var callSite = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is InvocationExpressionSyntax
                    {
                        Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "Which" },
                    },
                transform: static (ctx, _) =>
                {
                    var invocation = (InvocationExpressionSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetSymbolInfo(invocation).Symbol;
                    if (symbol?.ContainingType?.Name != "Interceptable") return null;

                    var member = (MemberAccessExpressionSyntax)invocation.Expression;
                    return ctx.SemanticModel.GetInterceptableLocation(invocation);
                })
            .Where(static location => location is not null);

        context.RegisterSourceOutput(callSite, static (production, location) =>
        {
            if (location is null) return;

            // `InterceptsLocationAttribute` is not in the BCL — a generator that
            // uses interceptors is expected to declare it itself.
            var source = $$"""
                // <auto-generated/> by Generator.FeatureGenerator.
                namespace System.Runtime.CompilerServices
                {
                    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]
                    file sealed class InterceptsLocationAttribute : System.Attribute
                    {
                        public InterceptsLocationAttribute(int version, string data)
                        {
                            Version = version;
                            Data = data;
                        }

                        public int Version { get; }
                        public string Data { get; }
                    }
                }

                namespace AdvancedFeatures
                {
                    file static class Interception
                    {
                        {{location.GetInterceptsLocationAttributeSyntax()}}
                        public static string Intercepted() => "intercepted";
                    }
                }
                """;
            production.AddSource("Interception.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}
