[package]
name = "rustclr-interop"
description = "Interop Bridge: P/Invoke and FFI for RustCLR"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rustclr-core.workspace = true
rustclr-gc.workspace = true
